import type { Feature } from '@/types'

export const FEATURES: Feature[] = [
  {
    id: 'scribe',
    title: 'AI Clinical Scribe',
    description: 'Doctor speaks after consultation. AI generates SOAP notes, ICD-10 codes, and prescription draft in under 2 minutes. Saves 12+ hours weekly.',
    icon: 'IconMic',
    phase: 'P0',
    audience: 'doctor',
  },
  {
    id: 'symptom',
    title: 'AI Symptom Checker',
    description: 'Patient describes symptoms in English, Tamil, or Hindi. AI asks adaptive follow-up questions and classifies urgency into 4 levels.',
    icon: 'IconBrain',
    phase: 'P0',
    audience: 'patient',
  },
  {
    id: 'appointment',
    title: 'Intelligent Appointment Booking',
    description: 'Natural language booking — "I need a cardiologist Saturday morning". Real-time slot display, confirmation, and automated reminders.',
    icon: 'IconCalendar',
    phase: 'P0',
    audience: 'patient',
  },
  {
    id: 'briefing',
    title: 'Pre-Consultation Briefing',
    description: 'AI compiles patient history, recent labs, allergies, and red flags into a structured brief — delivered to the doctor 10 minutes before the appointment.',
    icon: 'IconFileText',
    phase: 'P0',
    audience: 'doctor',
  },
  {
    id: 'drug',
    title: 'Drug Interaction Checker',
    description: 'Real-time safety co-pilot. Checks drug-drug interactions and allergies as the doctor types the prescription. Suggests generic alternatives.',
    icon: 'IconPill',
    phase: 'P0',
    audience: 'doctor',
  },
  {
    id: 'lab',
    title: 'Lab Report Interpreter',
    description: 'Patient uploads a PDF or photo. AI extracts all parameters via OCR and explains each one in plain language. Tracks trends over time.',
    icon: 'IconChart',
    phase: 'P1',
    audience: 'patient',
  },
  {
    id: 'followup',
    title: 'Post-Discharge Follow-Up',
    description: 'Automated WhatsApp follow-up 48 hours after every visit. Collects structured responses. Escalates to doctor immediately if red-flag symptoms detected.',
    icon: 'IconUsers',
    phase: 'P1',
    audience: 'doctor',
  },
  {
    id: 'concierge',
    title: 'Personal Health Concierge',
    description: 'Medication reminders, health journal, family profile management, and preventive care nudges — all via WhatsApp.',
    icon: 'IconShield',
    phase: 'P1',
    audience: 'patient',
  },
  {
    id: 'cdss',
    title: 'Clinical Decision Support',
    description: 'Evidence-based medical Q&A powered by RAG. Sourced from ICMR, WHO, and AHA guidelines. Never generates unsourced clinical claims.',
    icon: 'IconStethoscope',
    phase: 'P1',
    audience: 'doctor',
  },
  {
    id: 'referral',
    title: 'Referral & Letter Generation',
    description: 'One-click referral letters, discharge summaries, and medico-legal certificates — pre-filled, branded, and sendable via WhatsApp.',
    icon: 'IconFileText',
    phase: 'P1',
    audience: 'doctor',
  },
]
