import { IconMic, IconBuilding, IconUser } from '@icons/index'

export const PLATFORM_PRODUCTS = [
  {
    id: 'elthdoc',
    tag: 'For Doctors',
    title: 'ElthDoc',
    subtitle: 'AI-powered clinical workspace for every outpatient doctor',
    ctaText: 'Explore ElthDoc',
    ctaLink: '/for-doctors',
    icon: IconMic,
    img: '/images/elthDoc_1.png',
    color: '#3E7767',
    bg: '#22463B',
    features: [
      'Voice-first documentation',
      'Smart suggestions',
      'Auto-structured clinical notes',
      'Seamless workflows',
      'Complete patient context',
      'More time for patients',
    ],
  },
  {
    id: 'elthcare',
    tag: 'For Hospitals',
    title: 'ElthCare',
    subtitle: 'AI-powered hospital operations and care coordination at scale',
    ctaText: 'Explore ElthCare',
    ctaLink: '/for-hospitals',
    icon: IconBuilding,
    img: '/images/elthCare_1.png',
    color: '#4C6690',
    bg: '#293A54',
    features: [
      'Real-time operational overview',
      'Population health insights',
      'Care quality and outcomes',
      'Interoperability & data exchange',
      'Resource and capacity optimization',
      'Compliance, security & governance',
    ],
  },
  {
    id: 'myelth',
    tag: 'For Patients',
    title: 'MyElth',
    subtitle: 'A personal health companion that keeps your records organized, your privacy protected and you connected to the care that matters.',
    ctaText: 'Explore MyElth',
    ctaLink: '/for-patients',
    icon: IconUser,
    img: '/images/myElth_1.png',
    color: '#A87742',
    bg: '#4A3620',
    features: [
      'Access all your health records in one place',
      "Share only what's needed, with your consent",
      'Get reminders for medicines and appointments',
      'Stay connected with your doctors',
      'Track your health and stay informed',
    ],
  },
] as const
