import type { Testimonial } from '@/types'

export const TESTIMONIALS: Testimonial[] = [
  {
    quote: "The AI scribe has given me back 2 hours every single day. I can finally spend that time with my patients instead of typing notes.",
    name: 'Dr. Priya Ramachandran',
    role: 'Endocrinologist',
    hospital: 'Varsha Health Care',
    location: 'Coimbatore',
    avatar: '/images/avatars/dr-priya.jpg',
    initials: 'PR',
    bgColor: '#EEEDFE',
    textColor: '#26215C',
  },
  {
    quote: "My patients in Madurai finally understand their lab reports. The plain-language explanations in Tamil have reduced unnecessary panic calls to our clinic by 40%.",
    name: 'Dr. Suresh Natarajan',
    role: 'General Physician',
    hospital: 'Sri Kumaran Clinic',
    location: 'Madurai',
    avatar: '/images/avatars/dr-suresh.jpg',
    initials: 'SN',
    bgColor: '#E1F5EE',
    textColor: '#085041',
  },
  {
    quote: "We onboarded 500 patients in the first month. The WhatsApp-first approach works perfectly for our Tier-2 patient base who aren't comfortable with apps.",
    name: 'Vijay Kumar',
    role: 'Hospital Administrator',
    hospital: 'Varsha Health Care',
    location: 'Coimbatore',
    avatar: '/images/avatars/vijay.jpg',
    initials: 'VK',
    bgColor: '#E6F1FB',
    textColor: '#042C53',
  },
  {
    quote: "The pre-consultation brief is a game changer. I walk into every appointment knowing exactly what to focus on. No more asking patients to repeat their history.",
    name: 'Dr. Meenakshi Iyer',
    role: 'Cardiologist',
    hospital: 'Apollo Hospitals',
    location: 'Chennai',
    avatar: '/images/avatars/dr-meenakshi.jpg',
    initials: 'MI',
    bgColor: '#FAEEDA',
    textColor: '#412402',
  },
  {
    quote: "The drug interaction checker caught a potentially dangerous combination I almost missed during a busy OPD. It's saved me more than once.",
    name: 'Dr. Ramesh Balakrishnan',
    role: 'General Physician',
    hospital: 'Balaji Medical Centre',
    location: 'Chennai',
    avatar: '/images/avatars/dr-ramesh.jpg',
    initials: 'RB',
    bgColor: '#EEEDFE',
    textColor: '#26215C',
  },
  {
    quote: "Our no-show rate dropped 28% after enabling the automated appointment reminders. That's real revenue recovered, not just a nice stat.",
    name: 'Anitha Krishnan',
    role: 'Operations Head',
    hospital: 'Medanta Coimbatore',
    location: 'Coimbatore',
    avatar: '/images/avatars/anitha.jpg',
    initials: 'AK',
    bgColor: '#E1F5EE',
    textColor: '#085041',
  },
]
